### ISSUE TITLE
"unknow error" at "forget password"

### ISSUE THREAD

**Issue by JiangXL** [SUSTC/oursustc-node#5]
My classmate forget her sustc.us pwd and try to reset it.
But it show "unknow error" after enter all the info .
It happens on me too.I sure my CAS is right ,but...

**Comment by iamhyc** [comment]
@tengattack

**Comment by ProfFan** [comment]
想起来了，改OAuth了。。。

**Comment by JiangXL** [comment]
现在还没修好吗？@tengattack @ProfFan

**Comment by iamhyc** [comment]
@JiangXL 要重置密码，可以人工；说什么修好，先让论坛活跃起来再说吧

**Comment by JiangXL** [comment]
收到
